version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "investec-poller"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-apzyznpza5us"
s3_prefix = "investec-poller"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

