AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  investec

  Sample SAM Template for investec

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  InvestectTransactions:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  PollFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Policies:
      -  DynamoDBCrudPolicy:
          TableName: !Ref InvestectTransactions
    Properties:
      CodeUri: poll/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Environment:
        Variables:
          INVESTEC_CLIENT_ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          INVESTEC_SECRET:    xxxxxxxxxxxxxxxx
          INVESTEC_ACCOUNT_NUMBER: 00000000000
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(* * * * ? *)

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PollFunction:
    Description: "Download transactions from investec and push them to ddb"
    Value: !GetAtt PollFunction.Arn
  PollFunctionIamRole:
    Description: "Implicit IAM Role created for Investec poller function"
    Value: !GetAtt PollFunctionRole.Arn
